# Generated by Django 5.0 on 2023-12-20 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_inmessages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmessages',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
