# Generated by Django 5.0 on 2023-12-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_quizadditionalfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(null=True, verbose_name='Demands'),
        ),
    ]
