# Generated by Django 5.0 on 2023-12-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_vacancy_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='vacancy_photos/'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
